- name: Update system packages (Using YUM for Amazon Linux/RHEL)
  ansible.builtin.yum:  # CAMBIO: Usamos yum en lugar de apt
    name: '*'
    state: latest
    update_cache: yes
  become: true

- name: Install required system dependencies (Using YUM for Amazon Linux/RHEL)
  ansible.builtin.yum: # CAMBIO: Usamos yum en lugar de apt
    name:
      - python3
      - python3-pip
      - git
      - make
      # Nota: python3-venv no es siempre un paquete separado en RHEL/Amazon Linux; 
      # a menudo se incluye con python3 o se usa 'python3 -m venv'.
    state: present
  become: true

- name: Clone the Flask application repository
  git:
    repo: "{{ app_repo }}"
    dest: "{{ app_dest }}"
    version: "{{ app_branch }}"
  become: true

- name: Create Python virtual environment
  command: python3 -m venv venv
  args:
    chdir: "{{ app_dest }}"
  become: true

- name: Install Python dependencies with pip
  shell: |
    source venv/bin/activate
    pip install -e .[dev] --break-system-packages || pip install -e .[dev]
  args:
    chdir: "{{ app_dest }}"
  become: true

- name: Deploy systemd service for Flask app
  template:
    src: app.service.j2
    dest: /etc/systemd/system/carprice.service
  become: true

- name: Enable and start Flask app service
  systemd:
    name: carprice
    enabled: true
    state: started
  become: true

  